object Dependencies {
    const val coreKtx = "androidx.core:core-ktx:${Version.coreKtx}"
    const val appCompat = "androidx.appcompat:appcompat:${Version.appCompat}"
    const val material = "com.google.android.material:material:${Version.material}"
    const val constraint = "androidx.constraintlayout:constraintlayout:${Version.constraint}"
    const val fragmentKtx = "androidx.fragment:fragment-ktx:${Version.fragmentKtx}"
    const val dataStore = "androidx.datastore:datastore-preferences:${Version.dataStore}"
    const val viewBinding = "com.github.kirich1409:viewbindingpropertydelegate:${Version.viewBinding}"
    const val cicerone = "com.github.terrakok:cicerone:${Version.cicerone}"
    const val coroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Version.coroutines}"
    const val lifecycleViewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Version.lifecycle}"
    const val lifecycleRuntime = "androidx.lifecycle:lifecycle-runtime-ktx:${Version.lifecycle}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Version.retrofit}"
    const val okhttp = "com.squareup.okhttp3:okhttp:${Version.okhttp}"
    const val okhttpInterceptor = "com.squareup.okhttp3:logging-interceptor:${Version.okhttp}"
    const val serializationJson = "org.jetbrains.kotlinx:kotlinx-serialization-json:${Version.serializationJson}"
    const val serializationConverter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:${Version.serializationConverter}"
    const val dagger = "com.google.dagger:dagger:${Version.dagger}"
    const val daggerCompiler = "com.google.dagger:dagger-compiler:${Version.dagger}"
}