object Version {

    const val kotlin = "1.6.10"
    const val gradle = "7.1.2"

    const val coreKtx = "1.7.0"
    const val appCompat = "1.4.1"
    const val material = "1.4.0"
    const val constraint = "2.1.3"
    const val fragmentKtx = "1.4.1"
    const val recyclerView = "1.2.1"
    const val dataStore = "1.0.0"
    const val coroutines = "1.6.4"
    const val viewBinding = "1.5.6"
    const val cicerone = "7.1"
    const val lifecycle = "2.4.1"
    const val retrofit = "2.9.0"
    const val okhttp = "4.9.3"
    const val coil = "1.4.0"
    const val serializationJson = "1.3.2"
    const val serializationConverter = "0.8.0"
    const val timber = "5.0.1"
    const val dagger = "2.41"
    const val accompanist = "0.24.1-alpha"
}